#%RAML 1.0 NamedExample
[{
  Name: "Burlington Textiles Corp of America",
  accountNumber: "CD656092",
  Phone: "(336) 222-7000",
  Type: "Cutomer - Channel",
  Site: "NW",
  account_id__c: 55667702
}]